In [1]:
from numpy import *
a =  array([7,4,3,8])
b =  array([1,2,3,4])

In [2]:
arange(10, 30, 5) #add 5 to first number till you get second one

array([10, 15, 20, 25])

In [3]:
print( mean(a))  #arithmetic mean (mediana)

5.5


In [4]:
print( std(b)) #idk what it is

1.118033988749895


In [5]:
a.shape

(4,)

In [6]:
a =  linspace(2, 5, 10) # 2 + (5-3)/10 ## in 

In [7]:
a[0] #first number in array

2.0

In [8]:
a <3 #elements smaller that 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [9]:
print( append(b,[1,2,3,4],axis=0))     #put something (where, [what], which axis)     #[what] can be code too 

[1 2 3 4 1 2 3 4]


In [10]:
print( insert(a,0,b))     # add something at the end

[1.         2.         3.         4.         2.         2.33333333
 2.66666667 3.         3.33333333 3.66666667 4.         4.33333333
 4.66666667 5.        ]


In [11]:
print( sort(a))

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


In [12]:
shape(a)

(10,)

In [13]:
#newaxis(a)
reshape(a,(2,5))

array([[2.        , 2.33333333, 2.66666667, 3.        , 3.33333333],
       [3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ]])

In [14]:
shape(a)

(10,)

In [15]:
#other
#linspace()